const express = require('express')

const signupRouter = require('./signup')
const loginRouter = require('./login')
const passwordResetRouter = require('./passwordReset')
const deleteAccountRouter = require('./deleteAccount')
const profileRouter = require('./profile')
const profileAvatarRouter = require('./profileAvatar')
const profilePasswordRouter = require('./profilePassword')
const profileEmailRouter = require('./profileEmail')
const profileIdVerificationRouter = require('./profileIdVerification')
const profileCoreRouter = require('./profileCore')
const profileAdminRouter = require('./profileAdmin')
const profileBusinessOwnerRouter = require('./profileBusinessOwner')
const profileFirstLoginRouter = require('./profileFirstLogin')
const mfaRouter = require('./mfa')
const mfaBootstrapRouter = require('./mfaBootstrap')
const webauthnRouter = require('./webauthn')
const staffRecoveryRouter = require('./staffRecovery')
const staffDeletionRouter = require('./staffDeletion')
const adminDeletionRouter = require('./adminDeletion')
const sessionRouter = require('./session')
const adminUsersRouter = require('./adminUsers')

const router = express.Router()

// Compose feature routers under /api/auth
router.use('/', signupRouter)
router.use('/', loginRouter)
router.use('/', passwordResetRouter)
router.use('/', deleteAccountRouter)
router.use('/', profileRouter)
router.use('/', profileAvatarRouter)
router.use('/', profilePasswordRouter)
router.use('/', profileEmailRouter)
router.use('/', profileIdVerificationRouter)
router.use('/', profileCoreRouter)
router.use('/', profileAdminRouter)
router.use('/', profileBusinessOwnerRouter)
router.use('/', profileFirstLoginRouter)
router.use('/', mfaRouter)
router.use('/', mfaBootstrapRouter)
router.use('/', webauthnRouter)
router.use('/', staffRecoveryRouter)
router.use('/', staffDeletionRouter)
router.use('/', adminDeletionRouter)
router.use('/', sessionRouter)
router.use('/', adminUsersRouter)

module.exports = router
