const mongoose = require("mongoose");

const AuditLogSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
    eventType: {
      type: String,
      required: true,
      enum: [
        "profile_update",
        "password_change",
        "account_deletion",
        "mfa_enabled",
        "mfa_disabled",
        "login",
        "logout",
        "admin_approval",
        "admin_rejection",
        "document_upload",
        "document_delete",
        "role_change",
        "account_lock",
        "account_unlock",
        "email_change",
        "phone_change",
        "business_application_submitted",
        "business_added",
        "business_updated",
        "fee_config_created",
        "fee_config_updated",
        "fee_config_deleted",
        "regulatory_fee_config_updated",
        "other",
        "business_deleted",
        "primary_business_changed",
        "risk_profile_updated",
        "business_application_submitted",
        "business_retirement_requested",
        "business_retirement_verified",
        "business_retirement_confirmed",
        "business_retirement_rejected",
        "business_renewal_started",
        "business_renewal_submitted",
        "business_renewal_approved",
        "business_renewal_rejected",
        "inspection_created",
        "inspection_started",
        "inspection_submitted",
        "inspection_checklist_updated",
        "inspection_evidence_uploaded",
        "inspection_gps_mismatch",
        "inspection_acknowledged",
        "violation_issued",
        "violation_acknowledged",
        "violation_resolved",
        "appeal_submitted",
        "appeal_updated",
        "appeal_resolved",
        "payment_created",
        "payment_completed",
        "payment_cancelled",
        "permit_review_started",
        "permit_review",
        "application_claimed",
        "application_released",
        "application_transferred",
        "decision_revoked",
        "occupational_permit_created",
        "occupational_permit_updated",
        "general_permit_created",
        "general_permit_updated",
        "edit_request_submitted",
        "edit_request_resolved",
        "post_requirement_created",
        "post_requirement_updated",
        "walk_in_registered",
        "security_event",
        "restricted_field_attempt",
        "error_critical",
      ],
      index: true,
    },
    fieldChanged: {
      type: String,
      required: false,
      enum: [
        "email",
        "password",
        "firstName",
        "lastName",
        "phoneNumber",
        "id",
        "idType",
        "idNumber",
        "dateOfBirth",
        "avatar",
        "termsAccepted",
        "mfa",
        "role",
        "office",
        "department",
        "security",
        "system",
        "account",
        "session",
        "recovery",
        "maintenance",
        // Business profile fields
        "ownerIdentity",
        "consent",
        "businessInfo",
        "contactInfo",
        "applicationStatus",
        "businesses",
        "fee_config",
        "regulatory_fee_config",
        "inspection",
        "violation",
        "appeal",
        "payment",
        "permit",
        "retirement",
        "renewal",
      ],
    },
    oldValue: {
      type: String,
      default: "",
    },
    newValue: {
      type: String,
      default: "",
    },
    hash: {
      type: String,
      required: false,
      sparse: true,
      index: true,
    },
    txHash: {
      type: String,
      default: "",
      index: true,
    },
    blockNumber: {
      type: Number,
      default: null,
    },
    role: {
      type: String,
      required: true,
    },
    metadata: {
      type: mongoose.Schema.Types.Mixed,
      default: {},
    },
    blockchainStatus: {
      type: String,
      enum: ["pending", "anchored", "failed", "skipped"],
      default: "pending",
      index: true,
    },
    blockchainError: { type: String, default: "" },
    blockchainRetries: { type: Number, default: 0 },
    verified: {
      type: Boolean,
      default: false,
    },
    verifiedAt: {
      type: Date,
      default: null,
    },
  },
  { timestamps: true },
);

const { encryptionPlugin } = require("../../../../shared/lib/encryptionPlugin");
AuditLogSchema.plugin(encryptionPlugin, {
  fields: ["oldValue", "newValue", "role", "blockchainError"],
  deterministicFields: ["hash"],
  nestedPaths: [],
  arrayPaths: [],
  mixedPaths: ["metadata"],
});

AuditLogSchema.index({ userId: 1, createdAt: -1 });
AuditLogSchema.index({ eventType: 1, createdAt: -1 });

module.exports = mongoose.model("AuditLog", AuditLogSchema);
