export const PH_LOCATIONS = {
  provinces: [
    'Metro Manila',
    'Cebu',
    'Davao del Sur',
    'Laguna',
    'Cavite',
    'Bulacan',
    'Pampanga',
    'Benguet',
    'Iloilo',
    'Negros Occidental',
    'Bataan',
  ],
  citiesByProvince: {
    'Metro Manila': [
      'Manila',
      'Makati',
      'Quezon City',
      'Taguig',
      'Pasig',
      'Pasay',
      'Mandaluyong',
      'Marikina',
      'Parañaque',
      'Las Piñas',
      'Valenzuela',
      'Caloocan',
      'Navotas',
      'Malabon',
      'San Juan',
    ],
    Cebu: ['Cebu City', 'Mandaue', 'Lapu-Lapu', 'Talisay'],
    'Davao del Sur': ['Davao City'],
    Laguna: ['Santa Rosa', 'Calamba', 'San Pedro', 'Biñan'],
    Cavite: ['Bacoor', 'Imus', 'Dasmariñas', 'General Trias', 'Trece Martires'],
    Bulacan: ['San Jose del Monte', 'Malolos', 'Meycauayan', 'Santa Maria', 'Baliuag'],
    Pampanga: ['San Fernando', 'Angeles', 'Mabalacat'],
    Benguet: ['Baguio'],
    Iloilo: ['Iloilo City', 'Oton'],
    'Negros Occidental': ['Bacolod', 'Talisay', 'Silay'],
    Bataan: ['Balanga'],
  },
}